# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vericoldesin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 539)
        MainWindow.setStyleSheet("color: rgb(109, 112, 111)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Generate = QtWidgets.QPushButton(self.centralwidget)
        self.Generate.setGeometry(QtCore.QRect(190, 300, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Generate.setFont(font)
        self.Generate.setStyleSheet("background-color : rgb(236, 58, 26);\n"
"border-radius: 30px;\n"
"color: white;\n"
"border: 2px solid rgb(94, 94, 94)")
        self.Generate.setObjectName("Generate")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(220, 240, 261, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(220, 190, 231, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.generateparoles = QtWidgets.QLabel(self.centralwidget)
        self.generateparoles.setGeometry(QtCore.QRect(120, 70, 481, 71))
        self.generateparoles.setMinimumSize(QtCore.QSize(221, 71))
        self.generateparoles.setMaximumSize(QtCore.QSize(16777215, 71))
        self.generateparoles.setBaseSize(QtCore.QSize(15, 14))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.generateparoles.setFont(font)
        self.generateparoles.setObjectName("generateparoles")
        self.hereresult = QtWidgets.QLabel(self.centralwidget)
        self.hereresult.setGeometry(QtCore.QRect(260, 140, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hereresult.setFont(font)
        self.hereresult.setObjectName("hereresult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Generate.setText(_translate("MainWindow", "Згенерувати"))
        self.checkBox.setText(_translate("MainWindow", "Використвовувати алфавіт"))
        self.checkBox_2.setText(_translate("MainWindow", "використовувати числа"))
        self.generateparoles.setText(_translate("MainWindow", "генератор паролів"))
        self.hereresult.setText(_translate("MainWindow", "Тут буде результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
